spring:
  profiles.active: local
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
---
spring:
  profiles: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:~/test;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
