spring:
  profiles.active: local
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
---
spring:
  profiles: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: local
    password: local
    driver-class-name: org.h2.Driver
